name: "Docker Build and Push"
on:
    workflow_call:
      inputs:
        docker_username:
          required: true
          type: string
        image_name:
          required: true
          type: string
      secrets:
        DOCKER_HUB_TOKEN:
          required: true


jobs:
  docker-build-and-push:
#    needs: sonarcloud-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker_username }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build, Tag & Push Docker Image
        working-directory: complete
        run: |
          IMAGE_TAG=${{ inputs.docker_username }}/${{ inputs.image_name }}:${{ github.sha }}
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/\//-/g')
          COMMIT_ID=${{ github.sha }}
          echo "Image Tag: $IMAGE_TAG"
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG ${{ inputs.docker_username }}/${{ inputs.image_name }}-${BRANCH_NAME}:${{ github.sha }}
          docker tag $IMAGE_TAG ${{ inputs.docker_username }}/${{ inputs.image_name }}-${BRANCH_NAME}:latest
          docker push ${{ inputs.docker_username }}/${{ inputs.image_name }}-${BRANCH_NAME}:${{ github.sha }}
          docker push ${{ inputs.docker_username }}/${{ inputs.image_name }}-${BRANCH_NAME}:latest
