name: Orchestrator CI Pipeline
on:
  push:
    branches: [main, develop]
  workflow_dispatch:

env:
  IMAGE_NAME: spring-boot-app
  COMMIT_ID: ${{ github.sha }}
  JAVA_VERSION: 21
  SONAR_PROJECT_KEY: jogeshniwalkar_gs-spring-boot
  DOCKER_USERNAME: jogesh22

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      java_version: 21


  sonarcloud-scan:
    needs: build-and-test
    uses: ./.github/workflows/sonarcloud-scan.yml
    secrets: inherit
    #    secrets: ${{secrets.SONAR_TOKEN}}
    with:
      sonar_project_key: "jogeshniwalkar_gs-spring-boot"


  docker-build-and-push:
    needs: sonarcloud-scan
    uses: ./.github/workflows/docker-push.yml
    secrets: inherit
    #    secrets: ${{ secrets.DOCKER_HUB_TOKEN }}
    with:
      docker_username: 'jogesh22'
      image_name:  'spring-boot-app'

  notify-email:
    if: failure()
    needs: [ build-and-test, sonarcloud-scan, docker-build-and-push ]
    uses: ./.github/workflows/notify-email.yml
    secrets: inherit
#    secrets: ${{secrets.GMAIL_APP_PASSWORD}}

