name: Orchestrator CI Pipeline

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string
      sonar_project_key:
        required: true
        type: string
      docker_username:
        required: true
        type: string
      image_name:
        required: true
        type: string
      maven_goals:
        required: false
        type: string
        default: "clean verify"
      upload_reports:
        required: false
        type: boolean
        default: true


#env:
#  IMAGE_NAME: spring-boot-app
#  COMMIT_ID: ${{ github.sha }}
#  JAVA_VERSION: 21
#  SONAR_PROJECT_KEY: jogeshniwalkar_gs-spring-boot
#  DOCKER_USERNAME: jogesh22
#



jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      java_version: ${{inputs.java_version}}


  sonarcloud-scan:
    needs: build-and-test
    uses: ./.github/workflows/sonarcloud-scan.yml
    secrets: inherit
    #    secrets: ${{secrets.SONAR_TOKEN}}
    with:
      sonar_project_key: ${{inputs.sonar_project_key}}


  docker-build-and-push:
    needs: sonarcloud-scan
    uses: ./.github/workflows/docker-push.yml
    secrets: inherit
    #    secrets: ${{ secrets.DOCKER_HUB_TOKEN }}
    with:
      docker_username: ${{inputs.docker_username}}
      image_name: ${{inputs.image_name}}

  notify-email:
    needs: [ build-and-test, sonarcloud-scan, docker-build-and-push ]
    uses: ./.github/workflows/notify-email.yml
    secrets: inherit
#    secrets: ${{secrets.GMAIL_APP_PASSWORD}}

