name: Reusable SonarCloud Scan
on:
  workflow_call:
    inputs:
      sonar_project_key:
        required: true
        type: string

      upload_reports:
        required: false
        type: boolean
        default: true

    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonarcloud-scan:
#    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Prepare directory for binaries
        run: mkdir -p complete/target/classes

      - name: Download Compiled Classes
        uses: actions/download-artifact@v4
        with:
          name: compiled-classes
          path: complete/target/classes

      #      - name: Download Jacoco Report
      #        uses: actions/download-artifact@v4
      #        with:
      #          name: jacoco-report
      #          path: complete/target/site/jacoco/

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectBaseDir: complete
          args: >
            -Dsonar.projectKey=${{ inputs.SONAR_PROJECT_KEY }}
            -Dsonar.organization=jogeshniwalkar
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload coverage report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/*
